on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install pipenv
      - run: python -m pipenv install --skip-lock --dev
      - run: python -m pipenv run invoke dist
      # Now, pypa/gh-action-pypi-publish doesn't support major version tag
      # https://github.com/pypa/gh-action-pypi-publish/issues/22
      - uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          password: ${{ secrets.pypi_password }}
